import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    padding: 4,
    width: "100%",
  },
  title: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: 24,
    textAlign: "center",
  },
  qrContainer: {
    alignItems: "center",
    marginBottom: 24,
  },
  qrWrapper: {
    padding: 12,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#f1f5f9",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  qrHint: {
    marginTop: 12,
    fontSize: 13,
    color: "#64748b",
    fontWeight: "500",
  },
  infoContainer: {
    backgroundColor: "#f8fafc",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#f1f5f9",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 4,
  },
  label: {
    color: "#64748b",
    fontSize: 14,
    fontWeight: "500",
  },
  value: {
    color: "#1e293b",
    fontWeight: "700",
    fontSize: 16,
  },
  actions: {
    gap: 12,
  },
  pixButton: {
    backgroundColor: "#16a34a",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 14,
    gap: 10,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  linkButton: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 14,
    gap: 10,
  },
  linkButtonText: {
    color: "#475569",
    fontWeight: "600",
    fontSize: 15,
  },
  paidMessage: {
    alignItems: "center",
    paddingVertical: 10,
  },
  successIconBadge: {
    marginBottom: 12,
  },
  paidTextTitle: {
    color: "#15803d",
    fontWeight: "800",
    fontSize: 18,
    marginBottom: 4,
  },
  paidTextSubtitle: {
    color: "#64748b",
    fontSize: 14,
    textAlign: "center",
    paddingHorizontal: 20,
  },
  paidDate: {
    color: "#16a34a",
  },
  paidContainer: {
    alignItems: "center",
    paddingVertical: 10,
    gap: 16,
  },
  receiptButton: {
    backgroundColor: "#3b82f6",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    gap: 8,
    marginTop: 8,
    width: "100%",
  },
  receiptButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  warningContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#fef9c3",
    padding: 12,
    borderRadius: 12,
    marginTop: 8,
    width: "100%",
  },
  warningText: {
    flex: 1,
    fontSize: 13,
    color: "#854d0e",
    textAlign: "center",
  },
});
