import { colors } from "@/styles";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  hiddenWrapper: {
    position: "absolute",
    left: 0,
    top: 0,
    zIndex: -9999,
    opacity: 0,
  },
  cardContainer: {
    width: 580,
    height: 380,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  infoSection: {
    flex: 1,
    justifyContent: "space-between",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.primary,
    width: "100%",
    padding: 8,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#EEEEEE",
  },
  logo: {
    width: 120,
    height: 40,
  },
  userSection: {
    margin: 20,
    justifyContent: "center",
  },
  label: {
    fontSize: 10,
    color: "#888",
    marginBottom: 4,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  name: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#111",
    textTransform: "uppercase",
  },
  presentationText: {
    fontSize: 6,
    color: "#666",
    marginTop: 4,
  },
  footer: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.primary,
    width: "100%",
    padding: 8,
    borderTopWidth: 1,
    borderTopColor: "#EEEEEE",
  },
  documentText: {
    fontSize: 10,
    color: "#cecece",
  },
  qrSection: {
    width: 280,
    backgroundColor: "#F8F9FA",
    justifyContent: "center",
    alignItems: "center",
    borderLeftWidth: 2,
    borderLeftColor: "#E0E0E0",
    borderStyle: "dashed",
    padding: 20,
  },
  qrWrapper: {
    padding: 8,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#EEE",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  scanText: {
    marginTop: 16,
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
    textTransform: "uppercase",
  },
});
